### ISSUE TITLE
def.RawData undefined (type *grid.ActorDef has no field or method RawData) (solved,for others until resolved)

### ISSUE THREAD

**Issue by shimondoodkin** [dataux/dataux#10]
i had to patch with https://github.com/lytics/grid/pull/66/files

```
go get -u github.com/dataux/dataux
# github.com/dataux/dataux/planner
go/src/github.com/dataux/dataux/planner/server.go:57: def.RawData undefined (type *grid.ActorDef has no field or method RawData)
go/src/github.com/dataux/dataux/planner/sqlactor.go:122: m.def.RawData undefined (type *grid.ActorDef has no field or method RawData)
```

**Comment by araddon** [comment]
Sorry about that, I have a branch that should be much more stable that i will push up late tonight that has better Glock/Sync with dependencies.

**Comment by araddon** [comment]
Currently the Proxy-Server (receives mysql tcp conn) creates a query-plan and distributes these to the worker nodes, this distribution is done via etcd, I need to move it to a message instead of transferring via etcd (as may be larger than what should go through etcd).  Going to take a few days to get time to implement this, until then the only way to build is with that branch.

**Comment by araddon** [comment]
resolved
